### ISSUE TITLE
Tile Server 

### ISSUE THREAD

**Issue by amenk** [OpenPlaceGuide/openplaceguide#6]
Probably use Vector Tiles, they allow easier language switching

**Comment by amenk** [comment]
https://github.com/Gjacquenot/SelfHostedMapTileServerNotes

**Comment by amenk** [comment]
https://github.com/openmaptiles/openmaptiles/blob/master/QUICKSTART.md#check-tileserver

**Comment by amenk** [comment]
https://github.com/openmaptiles/openmaptiles/blob/master/UPDATE.md

``` 
$ make update-osm
Starting postgres docker compose target using default image (no recreate if exists)
Starting openmaptiles_postgres_1 ... done
Detected area=ethiopia based on finding a 'data/ethiopia.osm.pbf' file. Use 'area' parameter or environment variable to override.
docker-compose  run --rm --user=1000:1000 openmaptiles-tools sh -c 'pgwait && import-update'
[2022-01-15T15:05:56Z] 0:00:00 [fatal] Unable to read last.state.txt:open /import/last.state.txt: no such file or directory
make: *** [Makefile:401: update-osm] Fehler 1

**Comment by amenk** [comment]
zbycz recommended Makina maps: https://github.com/zbycz/osmapp/pull/86#issuecomment-1013941986 

will try ...

**Comment by amenk** [comment]
```
git clone --recurse-submodules https://github.com/makina-maps/makina-maps.git
git clone -b gh-pages https://github.com/openmaptiles/osm-bright-gl-style.git tileserver-gl/styles/osm-bright-gl-style
git clone -b gh-pages https://github.com/openmaptiles/klokantech-basic-gl-style.git tileserver-gl/styles/klokantech-basic-gl-style
git clone -b gh-pages https://github.com/makinacorpus/cassini-gl-style.git tileserver-gl/styles/cassini-gl-style
git clone -b gh-pages https://github.com/openmaptiles/fonts.git tileserver-gl/fonts
```


```
makina-maps/openmaptiles$ docker-compose down -v
ERROR: build path /home/me/mine/workspace/makina-maps/openmaptiles/openmaptiles-tools either does not exist, is not accessible, or is not a valid URL.
```

checked out master in the openmaptiles folder...


Download:

```
makina-maps/openmaptiles$ PROVIDER=osmfr ../scripts/20-import-prepare.sh africa/ethiopia
```

**Comment by amenk** [comment]
master does not work, but 

    cd openmaptiles
    git revert cd0d801257c10e2416923d7c6604510abbb4fdfa.

**Comment by amenk** [comment]
master does not work, but 

    cd openmaptiles
    git revert cd0d801257c10e2416923d7c6604510abbb4fdfa.

**Comment by amenk** [comment]
# Some area data like openstreetmap.fr can contain invalid references
# that must be cleaned up before using it for borders -- set it to true.
BORDERS_CLEANUP=false

**Comment by viniyan** [comment]
> Probably use Vector Tiles, they allow easier language switching

Hello, I'm currently trying to work with openstreetmaps tile server on kubernetes, could you help?

**Comment by amenk** [comment]
@viniyan I have no clue about kubernetes. What is your problem? Do you have a GitHub repo?

**Comment by viniyan** [comment]
Basically we have a deployment.yaml that doesn't work, its raising an error related to volume mount paths, but they are right.. Probably some OSM tile server specificity is causing this problem

**Comment by amenk** [comment]
I suggest you post on stackoverflow.com or such with the details. You can send me the link to the post here, and I can have a quick look if I can help

But in general it's off topic in this repo

**Comment by amenk** [comment]
we use makina maps successfully :-)
